
version: '3.2'

services: 

  gestion_espacios_fisicos_mid:

    image: golang:1.18-alpine
    container_name: ${API_NAME}
    volumes:
      - go_src:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    environment:
      - GO111MODULE=on
    env_file: 
      - .env
    ports: 
      - "${GESTION_ESPACIOS_FISICOS_MID_HTTP_PORT}:${GESTION_ESPACIOS_FISICOS_MID_HTTP_PORT}"  
    working_dir: /go/src
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -u github.com/beego/bee ;go get -v -u ./...; pwd;go mod init;bee migrate -driver=postgres -conn="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB}?sslmode=disable&search_path=public"; bee run -downdoc=true -gendoc=true'

  data_base:
    container_name: ${GESTION_ESPACIOS_FISICOS_MID_LOCAL}
    image: postgres:10.34-alpine
    volumes: 
        - postgres_data:/var/lib/postgresql/data
    ports: 
        - "${gestion_espacios_fisicos_mid_PGPORT}:${gestion_espacios_fisicos_mid_PGPORT}"        
    env_file: 
        - .env

volumes:
  go_src:
  postgres_data:
networks: 
  back_end:
    external: true